# Site settings
title: "Brittany Mederos"
email: "bm@enchant.co"
description: "Principal Design & Research Manager at Microsoft — Leading AI-driven design strategies and generative AI experiences."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.brittanymederos.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
